### PR TITLE
vertically center-align text in linespacing, fixes #415

### LINKED ISSUE #415: Vertical alignment problem of text
I think making the vertical alignment of the text slightly higher would be nice.

screen shot 2017-03-21 at 15 18 56

On the left is VimR (`v0.13.1-167`) and on the right is MacVim. They're both opening the same text file. VimR has `Line Spacing` option set to `0.90` and MacVim to `:set linespaces=-1` which make both almost identical in line space.

As you might be able to recognize, the vertical alignment of text in VimR is slightly lower such that the lower part of the character of "q", "y" and "g" are truncated whereas that's not the case for MacVim. I think it would be very nice if this can be modified (as in MacVim).

### PR DESCRIPTION
**Pull request by apaleslimghost**
this PR recreates #791

- [ ] check the rendering issue in https://github.com/qvacua/vimr/pull/791#issuecomment-646490411

### CODE REVIEW

**Comment by Asheq** [comment]
One thing that I'd like to point out in case it hasn't been considered: Even with line spacing there should be no gaps between [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character).

Take for example, the default vim option `fillchars`, for which the vertical separator between windows is a `|` character (`BOX DRAWINGS LIGHT VERTICAL`).

vimr (with `Line Spacing: 1.25`):
image

kitty terminal (with `adjust_line_height         125%`):
image

I don't know how kitty is doing this, but note how it appears as though there is one continuous line going all the way down because of the lack of gaps.

**Comment by qvacua** [comment]
Thank you for the PR (again) and sorry, I somehow missed this PR. I'll have a look at the weekend.

**Comment by apaleslimghost** [comment]
thanks! i likely won't have time to look into the issue you raised, sorry. i'm also not using vim any more! but it would still be great to see this merged :)

**Comment by qvacua** [comment]
I'm very sorry it took so long, however, it seems that the implementation still has some issues. I'll try to fix itL
Screenshot 2021-11-06 at 08 41 13

What font do you use?

**Comment by qvacua** [comment]
The correct computation is
```
base line offset = (line height + font height) / 2 - ascent
```
See https://github.com/qvacua/vimr/commit/f503b9e47e71310ab1e4adabbcb93ea13e334315.

**Pull request merged**
