### PR TITLE
Custom markdown processor setting

### PR DESCRIPTION
**Pull request by ernstwi**
Hello! Thanks for all the work on VimR.

This allows users to set a shell command to run instead of the default markdown processor. I saw there were some issues asking for different markdown features, which is probably unavoidable since there are so many variants of markdown. Personally I use pandoc with a lot of flags to get the specific markdown variant I prefer.

This is a work in progress but I wanted to get your input. Do you think this is a good idea? I was also unsure of where to put the setting. It is currently under "General" which I'm sure is not right, but should it go under "Tools" or "Advanced"? Or maybe in the cogwheel menu at the top of the preview window?

### CODE REVIEW

**Comment by qvacua** [comment]
Sorry for the late response. I think that the Advanced would do fine.

**Comment by qvacua** [comment]
I'm very sorry for being late. IMO "Advanced" would be the best fit for this setting. The forward and reverse search should be disabled without changing the settings value when a custom renderer is set. Also, one should check that the renderer exists when setting it.

**Comment by jottr** [comment]
@ernstwi did you give up on this feature?  

@qvacua did you ever try out the PR?

**Comment by ernstwi** [comment]
@jottr Sorry yes, I did give up on this.

In my case I already had a wiki server running locally which renders markdown how I like it, so it was more convenient to use VimR's HTML preview. I added a command [`VimRReloadWebview`](https://github.com/ernstwi/vimr/commit/6e03467a4110b33d13663d27952151bf59760c15) which takes an URL parameter. This let me sync HTML preview to the active buffer.

**Comment by qvacua** [comment]
I'm sorry for being mute for some time. I've been inactive due to some private reasons. I'll get slowly get restarted and go through all PRs.

**Pull request merged**
