### PR TITLE
Add option to change spacing between letters

### PR DESCRIPTION
**Pull request by tkonolige**
This PR adds a user option to change the spacing between letters. Its useful if you want more letters per line.

### CODE REVIEW

**Comment by qvacua** [comment]
Thanks! I'll have look at the PR in the weekend!

**Comment by qvacua** [comment]
I'll build a release once back home (around next week).

**Comment by tkonolige** [comment]
Great!

I really appreciate all the work you've done to make this app.

**Comment by bfulop** [comment]
I've been testing this version with the [Iosevka](https://typeof.net/Iosevka/) font, and it seems a bit off:

If I set the font spacing above `0.94` the spacing is much larger than on previous versions of Vimr.  
If I set it below `0.94` the letters are much more condensed.

#### Before

Screenshot 2019-04-27 at 16 16 03

#### After PR

Screenshot 2019-04-27 at 16 17 04

#### After PR, letter spacing at `0.93`

Screenshot 2019-04-27 at 16 17 24

**Comment by tkonolige** [comment]
If you remove the `ceil` calls from lines 24-52 does that fix the issue?

**Comment by tkonolige** [comment]
Can you see if #725 fixes this?

**Comment by bfulop** [comment]
Thank you @tkonolige for the quick reaction! 

I just tested it and indeed it does fix my issue! 
I have perfect control now on letter spacing! And the default 1.00 values seems now closer to the original value as it was before this update.

**Pull request merged**
