### PR TITLE
feat: provide neovim original commandline interface

### PR DESCRIPTION
**Pull request by SolaWing**
see #1001, this PR expose neovim original commandline interface. so plugin can create headless subprocess in same host binary.

seealso neovim patch https://github.com/qvacua/neovim/pull/3, should merge together

### CODE REVIEW

**Comment by georgeharker** [comment]
Thanks - I've been running with a dupe of this for a while, and it resolves several issues (eg. neogit not working).  Would be great to get these two patched in - thanks @SolaWing

**Comment by qvacua** [comment]
Thanks! I'll release a new version with this in the next days. Sorry, these days not much free time...

**Comment by mseri** [comment]
Any update on this?

**Comment by qvacua** [comment]
I'm sorry for being mute for some time. I've been inactive due to some private reasons. I'll get slowly get restarted and go through all PRs.

**Comment by georgeharker** [comment]
The PR that removes uibridge might be a better place to start as it allows more or less stock Nvim (and external ones too when the PR to neovim goes in). 

Hope all is ok.

**Comment by qvacua** [comment]
I'll merge this PR and other PRs first since @georgeharker 's PR could take some time, e.g., due to the dependency on his PR to Neovim.

**Pull request merged**
