### PR TITLE
Fix <Cmd + .> don't trigger keydown event.

### PR DESCRIPTION
**Pull request by imkerberos**

### CODE REVIEW

**Comment by qvacua** [comment]
`Cmd-.` is the shortcut for "Tools -> Focus Neovim View" menu item. Have you tried to delete the shortcut in the prefs?

**Comment by imkerberos** [comment]
Yes, I disabled all shortcuts in prefs.

**Comment by qvacua** [comment]
I see. I added a menu item shortcut check in the develop branch. Could you merge develop and check whether your that breaks your change?

**Comment by imkerberos** [comment]
@qvacua I have merged develop branch and checked. The menu shortcut checker doesn't break my change.

**Pull request merged**
